#DB_NAME: demoDb
#DB_SERVER: localhost
#DB_PORT: 3306
#DB_USERNAME: root
#DB_PASSWORD: rootpassword

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_SERVER}:${DB_PORT:3306}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
